version: '3.9'

services:
    vg-backend:
        image: jfang324/vg-backend:latest
        container_name: vg-backend
        env_file:
            - .env.backend
        restart: unless-stopped
        ports:
            - 3001:3001

    caddy:
        build:
            context: .
        develop:
            watch:
                - path: ./Caddyfile
                  action: rebuild
        image: caddy:2-alpine
        container_name: caddy
        depends_on:
            - vg-backend
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
            - caddy_config:/config
        restart: unless-stopped

volumes:
    caddy_data:
    caddy_config:
